[package]
name = "ArtewaldEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.31.1"
bytemuck = "1.8.0"

[profile.dev.package."*"]
opt-level = 3